# Generated by Django 5.0.1 on 2025-09-04 11:41
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_remove_post_blog_post_created_594d2d_idx_and_more'),
    ]

    operations = [
        TrigramExtension()
    ]
