# Generated by Django 5.2.6 on 2025-09-13 15:43
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_trigram_ext'),
    ]

    operations = [
        TrigramExtension()
    ]
